;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-electric-delete-forward
	c-electric-lt-gt
	indent-for-tab-command
	mozc-handle-event
	mwim-beginning-of-code-or-line
	mwim-end-of-code-or-line
	toggle-input-method
	wdired-finish-edit
	yas-expand
	))

(setq mc/cmds-to-run-once
      '(
	helm-M-x
	))
